-- DBUPDATE-031-0.SQL

-- Insert a new setting for OCR recognition
insert into T_CONFIG (CFG_ID_C, CFG_VALUE_C) values ('OCR_ENABLED', 'true');

-- Update the database version
update T_CONFIG set CFG_VALUE_C = '31' where CFG_ID_C = 'DB_VERSION';

CREATE CACHED TABLE T_USER_REQUEST (URQ_ID_C VARCHAR(36) NOT NULL, URQ_USERNAME_C VARCHAR(50) NOT NULL, URQ_EMAIL_C VARCHAR(100) NOT NULL, URQ_PASSWORD_C VARCHAR(255) NOT NULL, URQ_CREATEDATE_D DATETIME NOT NULL, URQ_STATUS_C VARCHAR(20) NOT NULL, PRIMARY KEY (URQ_ID_C), UNIQUE (URQ_USERNAME_C), UNIQUE (URQ_EMAIL_C))
CREATE INDEX IDX_URQ_CREATEDATE_D ON T_USER_REQUEST (URQ_CREATEDATE_D)
CREATE INDEX IDX_URQ_STATUS_C ON T_USER_REQUEST (URQ_STATUS_C)
update T_CONFIG set CFG_VALUE_C = '32' where CFG_ID_C = 'DB_VERSION'